_wandb:
    value:
        cli_version: 0.25.1
        e:
            h84d55hpaosrkbicbns8yb3epbx3c43g:
                args:
                    - --config
                    - configs/dae_resnet34.yaml
                codePath: src/train_dae.py
                codePathLocal: src/train_dae.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "258906374144"
                        used: "208663568384"
                email: tranduyvuong100@gmail.com
                executable: /home/ubuntu/thietkedenoiser/venv/bin/python3
                git:
                    commit: c1a165fde640142502ca376b926658831d249cc0
                    remote: https://github.com/vuongcris4/thietkedenoiser.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-ad80b35d-3b39-02ed-42fc-084896cd024e
                host: ip-172-31-17-210
                memory:
                    total: "16111902720"
                os: Linux-6.17.0-1009-aws-x86_64-with-glibc2.39
                program: /home/ubuntu/thietkedenoiser/src/train_dae.py
                python: CPython 3.12.3
                root: /home/ubuntu/thietkedenoiser
                startedAt: "2026-03-19T02:24:53.229962Z"
                writerId: h84d55hpaosrkbicbns8yb3epbx3c43g
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 63
                - 74
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.3
            "5": 0.25.1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
augment:
    value: true
data_root:
    value: data/OpenEarthMap
device:
    value: auto
img_size:
    value: 512
log_dir:
    value: results/logs
loss.boundary_weight:
    value: 0.5
loss.ce_weight:
    value: 1
loss.dice_weight:
    value: 1
model.encoder_name:
    value: resnet34
model.encoder_weights:
    value: imagenet
model.in_channels:
    value: 11
model.name:
    value: unet_resnet34
model.num_classes:
    value: 8
noise.rate_max:
    value: 0.3
noise.rate_min:
    value: 0.05
noise.type:
    value: mixed
num_classes:
    value: 8
num_workers:
    value: 2
pin_memory:
    value: true
save_dir:
    value: checkpoints
seed:
    value: 42
training.batch_size:
    value: 4
training.epochs:
    value: 100
training.lr:
    value: 0.0001
training.optimizer:
    value: adamw
training.patience:
    value: 15
training.scheduler:
    value: cosine
training.weight_decay:
    value: 0.0001
wandb.enabled:
    value: true
wandb.entity:
    value: null
wandb.project:
    value: thietkedenoiser
